-- Apache Derby schema for Miles of Smiles (embedded)
-- Note: If you are rerunning this script, please delete file-based DB path completely.

-- CUSTOMER table
CREATE TABLE CUSTOMER (
  ID INT PRIMARY KEY,
  NAME VARCHAR(64) NOT NULL,
  SURNAME VARCHAR(64) NOT NULL
);

CREATE INDEX IDX_CUSTOMER_NAME_SURNAME ON CUSTOMER (NAME, SURNAME);

-- BOOKING table
CREATE TABLE BOOKING (
  BOOKING_NUMBER VARCHAR(32) PRIMARY KEY,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  CANCELED SMALLINT NOT NULL DEFAULT 0,
  CAR_MODEL VARCHAR(64) NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  CONSTRAINT FK_BOOKING_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- Helpful index for lookups by customer
CREATE INDEX IDX_BOOKING_CUSTOMER ON BOOKING (CUSTOMER_ID);
